spring:
  h2:
    console:
      enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringTest?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    me.buri-1029: DEBUG

# echo 'buri-spring-boot-simple-test-jwt-login-buri-spring-boot-simple-test-jwt-login-buri-spring-boot-simple-test-jwt-login' | base64
jwt:
  header: Authorization
  secret: YnVyaS1zcHJpbmctYm9vdC1zaW1wbGUtdGVzdC1qd3QtbG9naW4tYnVyaS1zcHJpbmctYm9vdC1zaW1wbGUtdGVzdC1qd3QtbG9naW4tYnVyaS1zcHJpbmctYm9vdC1zaW1wbGUtdGVzdC1qd3QtbG9naW4K
  token-validity-in-seconds: 86400
